apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
  labels:
    app: blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue
          image: romango/clouddevopscapstone
          ports:
            - containerPort: 80